baseURL: https://nina-eriksson-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Nina Ferrer-Eriksson
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A PORTFOLIO
    title: Nina Ferrer-Eriksson Personal Website
  blog: {}
  contact:
    address: 
      - city: London
        country: United Kingdom
        street: Marylebone 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ninaaeriksson@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: +44 75 4780 0116
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.london.edu
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/nina__eriksson
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nina.eriksson.9469
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nj.eriksson
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/nina-eriksson
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ninafe
  image: ''
  name: Nina Ferrer-Eriksson
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Masters in Financial Analysis
        title: London Business School
        url: https://www.london.edu/
      - image: berenjack.jpeg
        subtitle: Don't forget book in advance
        title: Time to eat!
        url: https://berenjaklondon.com/
      - image: marylebone.jpeg
        subtitle: Home Sweet Home
        title: Marylebone
        url: https://www.marylebonevillage.com/
      - image: salva.jpeg
        subtitle: Coding Weekend
        title: The first website I created
        url: https://nina-eriksson.github.io/
      - image: djia.jpeg
        subtitle: DJIA stocks
        title: Risk & Return
        url: blogs/risk_return
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: See the lifestlye
    enable: yes
    subtitle: "You may write me down in history
 With your bitter, twisted lies,
You may trod me in the very dirt
But still, like dust, I'll rise.
"
    title: Poem by Maya Angelou
    url: blogs
markup: 
  goldmark: 
    renderer: 
      unsafe: true